"""create users table

Revision ID: 8fde1e2dffdd
Revises: ae6bbfaaa59a
Create Date: 2024-09-08 00:05:54.885623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fde1e2dffdd'
down_revision: Union[str, None] = 'ae6bbfaaa59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
